version: '3.9'

services:
  go-revel-crud:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - 8090:8090
    volumes:
      - .:/app
    environment:
      - ENV=dev
      - PORT=8090
      - DB_URL=postgres://go-revel-crud:go-revel-crud@postgres/go-revel-crud?sslmode=disable

  postgres:
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/go-revel-crud/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=go-revel-crud
      - POSTGRES_USER=go-revel-crud
      - POSTGRES_DB=go-revel-crud
